name: My first github actions #this is my new commit

on: [push]

jobs:
          build:
            runs-on: ubuntu latest

            strategy:
              matrix:
                python-version: [3.8,3.9]

            steps:
            - uses: actions/checkout@v3
            - name: set up Python
              uses: actions/setup-python@v2
              with:
                python-version: ${{ matrix.pythonversion }}

            - name: Install dependencies
              run: |
               python -m pip install  --upgrade pip
               pip install pytest

            - name: Run tests
              run: |
               cd src
               python -m pytest addition.py